### ISSUE TITLE
Use correct ids to identify trips and vehicles, include direction

### ISSUE THREAD

**Issue by Bertware** [julianrojas87/linked-connections-server#2]
Currently a departure contains the following information:
```
> "@id": "#1510063200000884906488____%3A007%3A%3A8846201%3A8400219%3A3%3A1501%3A20171208",
> "@type": "Connection",
> "departureStop": "http://irail.be/stations/NMBS/008849064",
> "arrivalStop": "http://irail.be/stations/NMBS/008400219",
> "departureTime": "2017-11-07T14:00:00.000Z",
> "arrivalTime": "2017-11-07T14:01:00.000Z",
> "gtfs:trip": "http://irail.be/trips/88____%3A007%3A%3A8846201%3A8400219%3A3%3A1501%3A20171208",
> "gtfs:route": "http://irail.be/routes/327
```

- @id should be formatted as a departureConnection id: `http://irail.be/connections/<station hafas id>/<yyyymmdd>/<train id>`, for example `http://irail.be/connections/8892007/20171107/IC532`. Hafas id is simply the station id without the leading zeros.

- gtfs:trip should be the trip id, which is a train trip on a certain day (correct me if I'm wrong): `http://irail.be/vehicle/{VehicleShortName}/{yyyymmdd}` where `VehicleShortName`is for example `IC532`
- gtfs:route should identify a route, with an identifier in the format `http://irail.be/vehicle/{VehicleShortName}`
- A field 'direction' should be included, containing a string which identifies the station name where this train is heading.

**Comment by julianrojas87** [comment]
Solved in the **irail** branch.
