### ISSUE TITLE
Wrong arrivalTime in connection

### ISSUE THREAD

**Issue by maximtmartin** [julianrojas87/linked-connections-server#23]
https://graph.irail.be/sncb/connections?departureTime=2019-01-10T08:16:00.000Z

connection ID: http://irail.be/connections/8896008/20190110/IC409

This connection (Kortrijk - Harelbeke) has the wrong arrivalTime, that of Welkenraedt.

```
{
@id: "http://irail.be/connections/8896008/20190110/IC409",
@type: "Connection",
departureStop: "http://irail.be/stations/NMBS/008896008",
arrivalStop: "http://irail.be/stations/NMBS/008896115",
departureTime: "2019-01-10T08:17:00.000Z",
arrivalTime: "2019-01-10T11:11:00.000Z",
gtfs:trip: "http://irail.be/vehicle/IC409/20190110",
gtfs:route: "http://irail.be/vehicle/IC409",
direction: "Welkenraedt",
gtfs:pickupType: "gtfs:Regular",
gtfs:dropOffType: "gtfs:Regular",
departureDelay: 0,
arrivalDelay: 0
}

**Comment by julianrojas87** [comment]
Sorry it took so long to address this. It is fixed now. It was due to a bug in how the real-time updates were processed. Thank you for pointing it out.
