### ISSUE TITLE
[High prio] Accept valid ISO8601 date stamps

### ISSUE THREAD

**Issue by Bertware** [julianrojas87/linked-connections-server#4]
Currently only dates formatted in UTC are accepted. Alternate timezones, which are accepted in ISO8601, should also be accepted.

> 
>  Complete date plus hours, minutes and seconds:
>       YYYY-MM-DDThh:mm:ssTZD (eg 1997-07-16T19:20:30+01:00)
>    Complete date plus hours, minutes, seconds and a decimal fraction of a
> second
>       YYYY-MM-DDThh:mm:ss.sTZD (eg 1997-07-16T19:20:30.45+01:00)
> 
> where:
> 
>      YYYY = four-digit year
>      MM   = two-digit month (01=January, etc.)
>      DD   = two-digit day of month (01 through 31)
>      hh   = two digits of hour (00 through 23) (am/pm NOT allowed)
>      mm   = two digits of minute (00 through 59)
>      ss   = two digits of second (00 through 59)
>      s    = one or more digits representing a decimal fraction of a second
>      TZD  = time zone designator (Z or +hh:mm or -hh:mm)
> 
https://www.w3.org/TR/NOTE-datetime

Currently UTC is a hardcoded requirement, even while the date might parse correctly:
https://github.com/julianrojas87/linked-connections-server/blob/master/src/routes/page-finder.js#L37

Example:
`https://graph.irail.be/sncb/connections?departureTime=2018-03-09T12:00:00.000+01:00`
won't be accepted and [will be rewritten to the actual time](https://github.com/julianrojas87/linked-connections-server/blob/master/src/routes/page-finder.js#L43)
`https://graph.irail.be/sncb/connections?departureTime=2018-03-09T18:20:00.000Z 
`

**Comment by julianrojas87** [comment]
I agree, the hardcoded restriction will be removed to support other date formats. However, query parameters must be properly encoded for them to be correctly recognized as dates. For example:

`https://graph.irail.be/sncb/connections?departureTime=2018-03-09T12:00:00.000+01:00`
won't be accepted as  the `+` sign will be replaced by a blank space, causing the date parsing to fail and thus resulting in a redirection to the actual time. Therefore the date must be provided like this:
`https://graph.irail.be/sncb/connections?departureTime=2018-03-09T12%3A00%3A00.000%2B01%3A00`

**Comment by julianrojas87** [comment]
Fixed on this [commit](https://github.com/julianrojas87/linked-connections-server/commit/6f6a052e32ce059e129ea016959e23952dd37f1a)
