### ISSUE TITLE
Don't use inconsistent date for folder naming in RT data

### ISSUE THREAD

**Issue by Bertware** [julianrojas87/linked-connections-server#5]
The realtime folder structure contains folders with names like '2018_4_12'. These names are hard to generate, especially now we don't use a fixed time interval anymore.
Instead, these folders should be named '2018-04-12', identical to the first part of each file it contains.
In other words, the folder name should be the shared prefix of every file it contains.

Example:
I have the static file 2018-04-07T17:34:00.000Z.jsonld.gz. I want to get the realtime data for this file.

I need to navigate to /real_time/{**_last_version_**}/{**_special_date_**}/2018-04-07T17:34:00.000Z.jsonld.
**_last_version_** is identical to the version field I used in the static file path. This is perfect, I can just reuse the same string.
Howevern, **_special_date_** requires me to take a substring of the filename, parse it as a date, print it as another date. By using the prefix of the file, I could just use a 10-digit substring.

**Comment by julianrojas87** [comment]
Not applicable anymore
