### ISSUE TITLE
GTFS file sorting includes lock file

### ISSUE THREAD

**Issue by Bertware** [julianrojas87/linked-connections-server#7]
when calling `readdir` in `getLatestGtfsSource`, the lock file is also included. This file doesn't end on .zip, causing the entire name to be interpreted as a Date.

https://github.com/julianrojas87/linked-connections-server/blob/master/lib/utils/utils.js#L493
```
2018-06-22T12:13:31.613Z - error:  RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at Utils.getLatestGtfsSource (linked-connections-server/lib/utils/utils.js:504:125)
    at <anonymous>
```

This doesn't seem to have a negative impact on the correct working, but should be resolved nonetheless. (Seems like low priority to me)

**Comment by julianrojas87** [comment]
Fixed here https://github.com/julianrojas87/linked-connections-server/commit/ce7ed59f40edafc0d71604273f79822b0f8bf5d7
